#!/usr/bin/with-contenv bash
echo "[openssh-server-tweaks] started"

if [ -n "$TWEAK_PROFILE_UMASK" ]; then
    echo "Setting profile umask to $TWEAK_PROFILE_UMASK"
    sed -i "s/^umask .*/umask $TWEAK_PROFILE_UMASK/" /etc/profile
fi

if [ -n "$TWEAK_USER_HOME" ]; then
    echo "Setting home of $USER_NAME to $TWEAK_USER_HOME"
    usermod --home "$TWEAK_USER_HOME" "$USER_NAME"
fi

if [ -n "$TWEAK_USERS_GID" ]; then
    echo "Setting gid of group users to $TWEAK_USERS_GID"
    groupmod -g "$TWEAK_USERS_GID" users
fi

echo "[openssh-server-tweaks] done"
